"""create packages table

Revision ID: 05ac31a74021
Revises:
Create Date: 2020-08-20 15:58:29.239679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ac31a74021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),  # noqa
    sa.Column('sender', sa.String(length=255), nullable=True),  # noqa
    sa.Column('recipient', sa.String(length=255), nullable=True),  # noqa
    sa.Column('origin', sa.String(length=255), nullable=True),  # noqa
    sa.Column('destination', sa.String(length=255), nullable=True),  # noqa
    sa.Column('location', sa.String(length=255), nullable=True),  # noqa
    sa.PrimaryKeyConstraint('id')  # noqa
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages')
    # ### end Alembic commands ###
